name: CSV Lint on CSV File Changes

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "data/**.csv"
      - ".github/workflows/csv-lint.yml"

jobs:
  csv-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: csvlinter
        uses: kcheriyath/csvlinter@V0.6.0
        with:
          find_pattern: "*.csv"
          fail_on_error: "true"
          extra_params: "--lazyquotes"